# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Carrito',
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Producto')),
                ('toppings', models.ManyToManyField(to='Producto.Topping')),
            ],
            options={
                'db_table': 'Elemento',
            },
        ),
        migrations.CreateModel(
            name='VentaRegistrada',
            fields=[
                ('id_Venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precioFinal', models.IntegerField(blank=True, null=True)),
                ('pizza', models.ManyToManyField(to='Vents.Elemento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Cliente')),
            ],
            options={
                'db_table': 'VentaRegistrada',
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='pizza',
            field=models.ManyToManyField(to='Vents.Elemento'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Cliente'),
        ),
    ]
