# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-17 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0002_tenantinactivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='franquicia',
            name='reportes_graficos',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='estado'),
        ),
    ]
