# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-18 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0003_franquicia_reportes_graficos'),
    ]

    operations = [
        migrations.AddField(
            model_name='franquicia',
            name='color',
            field=models.CharField(choices=[('red', 'Rojo'), ('purple', 'Morado'), ('orange', 'Naranja'), ('default', 'Default'), ('blue', 'Azul'), ('black', 'Negro')], default='default', max_length=20, verbose_name='color tema'),
        ),
        migrations.AddField(
            model_name='franquicia',
            name='font',
            field=models.CharField(choices=[('a', 'Defecto'), ('font-family: Mogra, cursive;', 'Mogra')], default='a', max_length=20, verbose_name='font'),
        ),
        migrations.AddField(
            model_name='franquicia',
            name='nav_var_color',
            field=models.CharField(choices=[('navbar-inverse', 'inverse'), ('navbar-default', 'default')], default='navbar-default', max_length=20, verbose_name='color nav-var'),
        ),
        migrations.AddField(
            model_name='franquicia',
            name='sidebar_grid',
            field=models.CharField(choices=[('a', 'No'), ('sidebar-grid', 'Si')], default='a', max_length=20, verbose_name='grid menu'),
        ),
        migrations.AddField(
            model_name='franquicia',
            name='tinte',
            field=models.CharField(choices=[('a', 'No'), ('flat-black', 'Si')], default='a', max_length=20, verbose_name='tinte'),
        ),
        migrations.AlterField(
            model_name='franquicia',
            name='reportes_graficos',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='reportes graficos'),
        ),
    ]
