# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-18 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0004_auto_20170617_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franquicia',
            name='font',
            field=models.CharField(choices=[('a', 'Defecto'), ('font-family: Mogra, cursive;', 'Mogra')], default='a', max_length=70, verbose_name='font'),
        ),
    ]
