# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0005_auto_20170617_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franquicia',
            name='font',
            field=models.CharField(choices=[('a', 'Defecto'), ('font-family: Mogra, cursive;', 'Mogra'), ('font-family: Josefin Sans, sans-serif;', 'Josefin Sans'), ('font-family: Pacifico, cursive;', 'Pacifico'), ('font-family: Shadows Into Light, cursive;', 'Shadows Into Light'), ('font-family: Gudea, sans-serif;', 'Gudea')], default='a', max_length=70, verbose_name='font'),
        ),
    ]
