# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('referencia', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=350, null=True)),
                ('numeroPorciones', models.IntegerField(blank=True, null=True)),
                ('precioBase', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='img/pizzas/', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=350, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'topping',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='toppings',
            field=models.ManyToManyField(to='Producto.Topping'),
        ),
    ]
