# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 19:59
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('tipo_documento_identificacion', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cedula de extranjeria')], max_length=20, verbose_name='tipo de identificacion')),
                ('numero_documento_identificacion', models.CharField(max_length=20, verbose_name='numero de documento de identificacion')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='correo electronico')),
                ('telefono', models.CharField(max_length=20, verbose_name='numero telefonico')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='estado')),
                ('primer_nombre', models.CharField(max_length=100, verbose_name='primer nombre')),
                ('segundo_nombre', models.CharField(default='', max_length=100, null=True, verbose_name='segundo nombre')),
                ('primer_apellido', models.CharField(max_length=100, verbose_name='primer apellido')),
                ('segundo_apellido', models.CharField(max_length=100, verbose_name='segundo apellido')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_cliente', models.BooleanField(default=False)),
                ('is_digitador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Usuario.Usuario')),
            ],
            options={
                'db_table': 'usuario_administrador',
            },
            bases=('Usuario.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Usuario.Usuario')),
                ('tarjeta_credito', models.CharField(max_length=200, verbose_name='numero de tarjeta de credito')),
            ],
            options={
                'db_table': 'usuario_cliente',
            },
            bases=('Usuario.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Digitador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Usuario.Usuario')),
            ],
            options={
                'db_table': 'usuario_digitador',
            },
            bases=('Usuario.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
