# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_cliente_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo_electronico',
            field=models.EmailField(max_length=100, verbose_name='correo electronico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento_identificacion',
            field=models.CharField(max_length=30, verbose_name='numero de documento de identificacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento_identificacion',
            field=models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cedula de extranjeria')], max_length=30, verbose_name='tipo de identificacion'),
        ),
    ]
